// Demo mock data — used when REACT_APP_BACKEND_URL is not configured
// Dates are computed relative to now so the demo always looks current

const now = new Date();
const d = (hours) => new Date(now.getTime() + hours * 3600000).toISOString();
const id = () => Math.random().toString(36).slice(2, 18);

export const MOCK_VESSELS = [
  {
    id: "v001", name: "MV Ocean Pride", imo_number: "9341820",
    ship_manager: "Anglo-Eastern Ship Management Mumbai",
    ship_owner: "GE Shipping",
    port: "Mumbai", eta: d(-6), etd: d(30), berth: "B-04",
    vessel_type: "Bulk Carrier", gross_tonnage: 42000, dwt: 75000, year_built: 2010,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(-24 * 5), days_remaining: -5, status: "expired" },
      { type: "FFA", expiry_date: d(24 * 4), days_remaining: 4, status: "critical" },
    ],
    relationship: "existing", call_status: "overdue",
    next_port: { name: "Singapore", code: "SGP", covered: false },
    assigned_engineer: "Rajan Nair", notes: [], created_at: d(-48),
  },
  {
    id: "v002", name: "MV Jade Emperor", imo_number: "9452311",
    ship_manager: "Synergy Marine Chennai",
    ship_owner: "Indian Oil Corporation",
    port: "Mumbai", eta: d(2), etd: d(50), berth: "B-11",
    vessel_type: "Product Tanker", gross_tonnage: 28000, dwt: 45000, year_built: 2015,
    service_types: ["FFA", "LSA"],
    certificates: [
      { type: "FFA", expiry_date: d(24 * 6), days_remaining: 6, status: "critical" },
      { type: "LSA", expiry_date: d(24 * 25), days_remaining: 25, status: "warning" },
    ],
    relationship: "existing", call_status: "called",
    next_port: { name: "Colombo", code: "LKA", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-24),
  },
  {
    id: "v003", name: "MV Star Navigator", imo_number: "9198745",
    ship_manager: "Fleet Management Ltd Mumbai",
    ship_owner: "Essar Shipping",
    port: "Kandla", eta: d(4), etd: d(60), berth: "B-07",
    vessel_type: "Container", gross_tonnage: 65000, dwt: 70000, year_built: 2018,
    service_types: ["LSA", "FFA", "NAVCOM"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 20), days_remaining: 20, status: "warning" },
      { type: "FFA", expiry_date: d(24 * 60), days_remaining: 60, status: "safe" },
      { type: "NAVCOM", expiry_date: d(24 * 3), days_remaining: 3, status: "critical" },
    ],
    relationship: "existing", call_status: "pending",
    next_port: { name: "Dubai", code: "ARE", covered: false },
    assigned_engineer: "Suresh Kumar", notes: [], created_at: d(-12),
  },
  {
    id: "v004", name: "MV Pearl Voyager", imo_number: "9563214",
    ship_manager: "BSM Ship Management Mumbai",
    ship_owner: "SCI India",
    port: "Kochi", eta: d(8), etd: d(72), berth: "B-02",
    vessel_type: "Chemical Tanker", gross_tonnage: 18000, dwt: 28000, year_built: 2012,
    service_types: ["FFA", "LSA"],
    certificates: [
      { type: "FFA", expiry_date: d(-24 * 2), days_remaining: -2, status: "expired" },
      { type: "LSA", expiry_date: d(24 * 90), days_remaining: 90, status: "safe" },
    ],
    relationship: "new_lead", call_status: "overdue",
    next_port: { name: "Fujairah", code: "ARE", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-36),
  },
  {
    id: "v005", name: "MV Golden Horizon", imo_number: "9312654",
    ship_manager: "V.Ships Singapore",
    ship_owner: "HPCL",
    port: "Chennai", eta: d(1), etd: d(40), berth: "B-15",
    vessel_type: "Product Tanker", gross_tonnage: 33000, dwt: 52000, year_built: 2008,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 14), days_remaining: 14, status: "warning" },
      { type: "FFA", expiry_date: d(24 * 45), days_remaining: 45, status: "safe" },
    ],
    relationship: "existing", call_status: "pending",
    next_port: { name: "Shanghai", code: "CHN", covered: false },
    assigned_engineer: "Priya Menon", notes: [], created_at: d(-8),
  },
  {
    id: "v006", name: "MV Sapphire Sea", imo_number: "9421035",
    ship_manager: "Wallem Shipmanagement Hong Kong",
    ship_owner: "Reliance Industries",
    port: "Vizag", eta: d(5), etd: d(55), berth: "B-09",
    vessel_type: "General Cargo", gross_tonnage: 22000, dwt: 35000, year_built: 2014,
    service_types: ["LSA", "FFA", "NAVCOM"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 5), days_remaining: 5, status: "critical" },
      { type: "FFA", expiry_date: d(24 * 28), days_remaining: 28, status: "warning" },
      { type: "NAVCOM", expiry_date: d(24 * 120), days_remaining: 120, status: "safe" },
    ],
    relationship: "existing", call_status: "called",
    next_port: { name: "Rotterdam", code: "NLD", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-20),
  },
  {
    id: "v007", name: "MV Iron Monarch", imo_number: "9234871",
    ship_manager: "Thome Ship Management Singapore",
    ship_owner: "Adani Logistics",
    port: "Mundra", eta: d(3), etd: d(45), berth: "B-18",
    vessel_type: "Bulk Carrier", gross_tonnage: 55000, dwt: 90000, year_built: 2007,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 2), days_remaining: 2, status: "critical" },
      { type: "FFA", expiry_date: d(24 * 7), days_remaining: 7, status: "critical" },
    ],
    relationship: "existing", call_status: "overdue",
    next_port: { name: "Yokohama", code: "JPN", covered: false },
    assigned_engineer: "Arjun Sharma", notes: [], created_at: d(-16),
  },
  {
    id: "v008", name: "MV Silver Dawn", imo_number: "9512087",
    ship_manager: "Columbia Shipmanagement Limassol",
    ship_owner: "Pacific Basin Shipping",
    port: "Tuticorin", eta: d(10), etd: d(80), berth: "B-05",
    vessel_type: "RORO", gross_tonnage: 30000, dwt: 38000, year_built: 2016,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 55), days_remaining: 55, status: "safe" },
      { type: "FFA", expiry_date: d(24 * 80), days_remaining: 80, status: "safe" },
    ],
    relationship: "new_lead", call_status: "pending",
    next_port: { name: "Hamburg", code: "DEU", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-5),
  },
  {
    id: "v009", name: "MV Crystal Wave", imo_number: "9387412",
    ship_manager: "Executive Ship Management Singapore",
    ship_owner: "Safe Bulkers Inc",
    port: "Mumbai", eta: d(6), etd: d(65), berth: "B-22",
    vessel_type: "Bulk Carrier", gross_tonnage: 48000, dwt: 82000, year_built: 2011,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(-24 * 1), days_remaining: -1, status: "expired" },
      { type: "FFA", expiry_date: d(24 * 18), days_remaining: 18, status: "warning" },
    ],
    relationship: "existing", call_status: "overdue",
    next_port: { name: "Singapore", code: "SGP", covered: false },
    assigned_engineer: "Rajan Nair", notes: [], created_at: d(-30),
  },
  {
    id: "v010", name: "MV Red Falcon", imo_number: "9456231",
    ship_manager: "Anglo-Eastern Ship Management Hong Kong",
    ship_owner: "Tsakos Energy Navigation",
    port: "Kandla", eta: d(12), etd: d(90), berth: "B-03",
    vessel_type: "Product Tanker", gross_tonnage: 26000, dwt: 42000, year_built: 2019,
    service_types: ["FFA", "LSA"],
    certificates: [
      { type: "FFA", expiry_date: d(24 * 30), days_remaining: 30, status: "warning" },
      { type: "LSA", expiry_date: d(24 * 95), days_remaining: 95, status: "safe" },
    ],
    relationship: "existing", call_status: "pending",
    next_port: { name: "Dubai", code: "ARE", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-10),
  },
  {
    id: "v011", name: "MV Neptune's Grace", imo_number: "9278534",
    ship_manager: "Synergy Marine Singapore",
    ship_owner: "Eastern Bulk Carriers AS",
    port: "Kochi", eta: d(2), etd: d(38), berth: "B-14",
    vessel_type: "Chemical Tanker", gross_tonnage: 15000, dwt: 24000, year_built: 2013,
    service_types: ["FFA", "LSA"],
    certificates: [
      { type: "FFA", expiry_date: d(24 * 1), days_remaining: 1, status: "critical" },
      { type: "LSA", expiry_date: d(24 * 12), days_remaining: 12, status: "warning" },
    ],
    relationship: "existing", call_status: "called",
    next_port: { name: "Colombo", code: "LKA", covered: false },
    assigned_engineer: "Suresh Kumar", notes: [], created_at: d(-18),
  },
  {
    id: "v012", name: "MV Coral Trader", imo_number: "9534127",
    ship_manager: "Fleet Management Ltd Mumbai",
    ship_owner: "GE Shipping",
    port: "Chennai", eta: d(7), etd: d(70), berth: "B-08",
    vessel_type: "Container", gross_tonnage: 72000, dwt: 78000, year_built: 2020,
    service_types: ["LSA", "FFA", "NAVCOM"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 75), days_remaining: 75, status: "safe" },
      { type: "FFA", expiry_date: d(24 * 110), days_remaining: 110, status: "safe" },
      { type: "NAVCOM", expiry_date: d(24 * 22), days_remaining: 22, status: "warning" },
    ],
    relationship: "existing", call_status: "pending",
    next_port: { name: "Shanghai", code: "CHN", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-7),
  },
  {
    id: "v013", name: "MV Phoenix Rising", imo_number: "9189043",
    ship_manager: "BSM Ship Management Mumbai",
    ship_owner: "Indian Oil Corporation",
    port: "Vizag", eta: d(15), etd: d(100), berth: "B-01",
    vessel_type: "General Cargo", gross_tonnage: 19000, dwt: 30000, year_built: 2009,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 40), days_remaining: 40, status: "safe" },
      { type: "FFA", expiry_date: d(24 * 8), days_remaining: 8, status: "critical" },
    ],
    relationship: "new_lead", call_status: "pending",
    next_port: { name: "Fujairah", code: "ARE", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-4),
  },
  {
    id: "v014", name: "MV Blue Marlin", imo_number: "9623418",
    ship_manager: "V.Ships Dubai",
    ship_owner: "HPCL",
    port: "Mundra", eta: d(9), etd: d(75), berth: "B-16",
    vessel_type: "Bulk Carrier", gross_tonnage: 60000, dwt: 95000, year_built: 2017,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(-24 * 3), days_remaining: -3, status: "expired" },
      { type: "FFA", expiry_date: d(24 * 50), days_remaining: 50, status: "safe" },
    ],
    relationship: "existing", call_status: "overdue",
    next_port: { name: "Rotterdam", code: "NLD", covered: false },
    assigned_engineer: "Arjun Sharma", notes: [], created_at: d(-40),
  },
  {
    id: "v015", name: "MV Pacific Champion", imo_number: "9356712",
    ship_manager: "Wallem Shipmanagement Hong Kong",
    ship_owner: "Reliance Industries",
    port: "Mumbai", eta: d(20), etd: d(120), berth: "B-20",
    vessel_type: "RORO", gross_tonnage: 35000, dwt: 44000, year_built: 2021,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 130), days_remaining: 130, status: "safe" },
      { type: "FFA", expiry_date: d(24 * 150), days_remaining: 150, status: "safe" },
    ],
    relationship: "existing", call_status: "called",
    next_port: { name: "Yokohama", code: "JPN", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-2),
  },
  {
    id: "v016", name: "MV Indian Express", imo_number: "9412589",
    ship_manager: "Anglo-Eastern Ship Management Mumbai",
    ship_owner: "SCI India",
    port: "Tuticorin", eta: d(3), etd: d(48), berth: "B-12",
    vessel_type: "Container", gross_tonnage: 68000, dwt: 74000, year_built: 2016,
    service_types: ["LSA", "FFA", "NAVCOM"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 9), days_remaining: 9, status: "critical" },
      { type: "FFA", expiry_date: d(24 * 27), days_remaining: 27, status: "warning" },
      { type: "NAVCOM", expiry_date: d(24 * 65), days_remaining: 65, status: "safe" },
    ],
    relationship: "existing", call_status: "pending",
    next_port: { name: "Hamburg", code: "DEU", covered: false },
    assigned_engineer: "Priya Menon", notes: [], created_at: d(-14),
  },
  {
    id: "v017", name: "MV Emerald Coast", imo_number: "9287634",
    ship_manager: "Synergy Marine Chennai",
    ship_owner: "Adani Logistics",
    port: "Kochi", eta: d(16), etd: d(110), berth: "B-06",
    vessel_type: "Chemical Tanker", gross_tonnage: 20000, dwt: 32000, year_built: 2014,
    service_types: ["FFA", "LSA"],
    certificates: [
      { type: "FFA", expiry_date: d(24 * 85), days_remaining: 85, status: "safe" },
      { type: "LSA", expiry_date: d(24 * 100), days_remaining: 100, status: "safe" },
    ],
    relationship: "new_lead", call_status: "pending",
    next_port: { name: "Singapore", code: "SGP", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-6),
  },
  {
    id: "v018", name: "MV Tiger Bay", imo_number: "9512043",
    ship_manager: "Columbia Shipmanagement Limassol",
    ship_owner: "Pacific Basin Shipping",
    port: "Chennai", eta: d(11), etd: d(85), berth: "B-17",
    vessel_type: "Bulk Carrier", gross_tonnage: 50000, dwt: 85000, year_built: 2013,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 16), days_remaining: 16, status: "warning" },
      { type: "FFA", expiry_date: d(-24 * 4), days_remaining: -4, status: "expired" },
    ],
    relationship: "existing", call_status: "overdue",
    next_port: { name: "Dubai", code: "ARE", covered: false },
    assigned_engineer: "Rajan Nair", notes: [], created_at: d(-25),
  },
  {
    id: "v019", name: "MV Monsoon Wind", imo_number: "9345621",
    ship_manager: "Executive Ship Management Singapore",
    ship_owner: "Safe Bulkers Inc",
    port: "Kandla", eta: d(18), etd: d(115), berth: "B-10",
    vessel_type: "General Cargo", gross_tonnage: 24000, dwt: 38000, year_built: 2010,
    service_types: ["LSA", "FFA", "NAVCOM"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 35), days_remaining: 35, status: "safe" },
      { type: "FFA", expiry_date: d(24 * 45), days_remaining: 45, status: "safe" },
      { type: "NAVCOM", expiry_date: d(24 * 15), days_remaining: 15, status: "warning" },
    ],
    relationship: "existing", call_status: "called",
    next_port: { name: "Colombo", code: "LKA", covered: false },
    assigned_engineer: "Suresh Kumar", notes: [], created_at: d(-9),
  },
  {
    id: "v020", name: "MV Dragon Star", imo_number: "9498231",
    ship_manager: "Thome Ship Management Singapore",
    ship_owner: "Tsakos Energy Navigation",
    port: "Vizag", eta: d(22), etd: d(130), berth: "B-13",
    vessel_type: "Product Tanker", gross_tonnage: 29000, dwt: 46000, year_built: 2022,
    service_types: ["FFA", "LSA"],
    certificates: [
      { type: "FFA", expiry_date: d(24 * 180), days_remaining: 180, status: "safe" },
      { type: "LSA", expiry_date: d(24 * 200), days_remaining: 200, status: "safe" },
    ],
    relationship: "existing", call_status: "pending",
    next_port: { name: "Shanghai", code: "CHN", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-3),
  },
  {
    id: "v021", name: "MV Deccan Queen", imo_number: "9234509",
    ship_manager: "Fleet Management Ltd Mumbai",
    ship_owner: "GE Shipping",
    port: "Mundra", eta: d(1), etd: d(35), berth: "B-19",
    vessel_type: "Bulk Carrier", gross_tonnage: 44000, dwt: 72000, year_built: 2006,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 3), days_remaining: 3, status: "critical" },
      { type: "FFA", expiry_date: d(-24 * 6), days_remaining: -6, status: "expired" },
    ],
    relationship: "existing", call_status: "overdue",
    next_port: { name: "Fujairah", code: "ARE", covered: false },
    assigned_engineer: "Arjun Sharma", notes: [], created_at: d(-50),
  },
  {
    id: "v022", name: "MV Malabar Spirit", imo_number: "9567834",
    ship_manager: "V.Ships Dubai",
    ship_owner: "Essar Shipping",
    port: "Mumbai", eta: d(14), etd: d(95), berth: "B-21",
    vessel_type: "Container", gross_tonnage: 58000, dwt: 64000, year_built: 2018,
    service_types: ["LSA", "FFA", "NAVCOM"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 50), days_remaining: 50, status: "safe" },
      { type: "FFA", expiry_date: d(24 * 70), days_remaining: 70, status: "safe" },
      { type: "NAVCOM", expiry_date: d(24 * 10), days_remaining: 10, status: "critical" },
    ],
    relationship: "existing", call_status: "pending",
    next_port: { name: "Rotterdam", code: "NLD", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-11),
  },
  {
    id: "v023", name: "MV Konkan Explorer", imo_number: "9412870",
    ship_manager: "BSM Ship Management Mumbai",
    ship_owner: "Indian Oil Corporation",
    port: "Tuticorin", eta: d(6), etd: d(58), berth: "B-25",
    vessel_type: "Chemical Tanker", gross_tonnage: 17000, dwt: 26000, year_built: 2015,
    service_types: ["FFA", "LSA"],
    certificates: [
      { type: "FFA", expiry_date: d(24 * 26), days_remaining: 26, status: "warning" },
      { type: "LSA", expiry_date: d(24 * 60), days_remaining: 60, status: "safe" },
    ],
    relationship: "existing", call_status: "called",
    next_port: { name: "Colombo", code: "LKA", covered: false },
    assigned_engineer: "Priya Menon", notes: [], created_at: d(-15),
  },
  {
    id: "v024", name: "MV Gujarat Pride", imo_number: "9298543",
    ship_manager: "Anglo-Eastern Ship Management Hong Kong",
    ship_owner: "HPCL",
    port: "Kandla", eta: d(0.5), etd: d(28), berth: "B-23",
    vessel_type: "Product Tanker", gross_tonnage: 31000, dwt: 50000, year_built: 2011,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(-24 * 8), days_remaining: -8, status: "expired" },
      { type: "FFA", expiry_date: d(24 * 2), days_remaining: 2, status: "critical" },
    ],
    relationship: "existing", call_status: "overdue",
    next_port: { name: "Dubai", code: "ARE", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-60),
  },
  {
    id: "v025", name: "MV Arctic Venture", imo_number: "9389210",
    ship_manager: "Synergy Marine Singapore",
    ship_owner: "Eastern Bulk Carriers AS",
    port: "Kochi", eta: d(25), etd: d(145), berth: "B-24",
    vessel_type: "RORO", gross_tonnage: 36000, dwt: 46000, year_built: 2019,
    service_types: ["LSA", "FFA"],
    certificates: [
      { type: "LSA", expiry_date: d(24 * 160), days_remaining: 160, status: "safe" },
      { type: "FFA", expiry_date: d(24 * 175), days_remaining: 175, status: "safe" },
    ],
    relationship: "new_lead", call_status: "pending",
    next_port: { name: "Yokohama", code: "JPN", covered: false },
    assigned_engineer: null, notes: [], created_at: d(-1),
  },
];

export const MOCK_JOBS = [
  { id: "j001", vessel_id: "v001", vessel_name: "MV Ocean Pride", ship_manager: "Anglo-Eastern Ship Management Mumbai", ship_owner: "GE Shipping", vessel_type: "Bulk Carrier", port: "Mumbai", berth: "B-04", eta: d(-6), etd: d(30), service_type: "LSA", cert_expiry_date: d(-24 * 5), cert_days_remaining: -5, cert_status: "expired", status: "in_progress", next_port: { name: "Singapore", code: "SGP", covered: false }, checklist: [{ item: "Lifeboat inspection", completed: true }, { item: "Life raft servicing", completed: true }, { item: "Life jacket count & condition", completed: false }, { item: "EPIRB battery test", completed: false }, { item: "Pyrotechnics expiry check", completed: false }], created_at: d(-48) },
  { id: "j002", vessel_id: "v001", vessel_name: "MV Ocean Pride", ship_manager: "Anglo-Eastern Ship Management Mumbai", ship_owner: "GE Shipping", vessel_type: "Bulk Carrier", port: "Mumbai", berth: "B-04", eta: d(-6), etd: d(30), service_type: "FFA", cert_expiry_date: d(24 * 4), cert_days_remaining: 4, cert_status: "critical", status: "pending", next_port: { name: "Singapore", code: "SGP", covered: false }, checklist: [{ item: "Fire extinguisher inspection", completed: false }, { item: "Fire hose pressure test", completed: false }, { item: "Fixed CO2 system check", completed: false }, { item: "Fire detection alarm test", completed: false }, { item: "Breathing apparatus service", completed: false }], created_at: d(-48) },
  { id: "j003", vessel_id: "v002", vessel_name: "MV Jade Emperor", ship_manager: "Synergy Marine Chennai", ship_owner: "Indian Oil Corporation", vessel_type: "Product Tanker", port: "Mumbai", berth: "B-11", eta: d(2), etd: d(50), service_type: "FFA", cert_expiry_date: d(24 * 6), cert_days_remaining: 6, cert_status: "critical", status: "acknowledged", next_port: { name: "Colombo", code: "LKA", covered: false }, checklist: [{ item: "Fire extinguisher inspection", completed: true }, { item: "Fire hose pressure test", completed: false }, { item: "Fixed CO2 system check", completed: false }, { item: "Fire detection alarm test", completed: false }, { item: "Breathing apparatus service", completed: false }], created_at: d(-24) },
  { id: "j004", vessel_id: "v003", vessel_name: "MV Star Navigator", ship_manager: "Fleet Management Ltd Mumbai", ship_owner: "Essar Shipping", vessel_type: "Container", port: "Kandla", berth: "B-07", eta: d(4), etd: d(60), service_type: "NAVCOM", cert_expiry_date: d(24 * 3), cert_days_remaining: 3, cert_status: "critical", status: "pending", next_port: { name: "Dubai", code: "ARE", covered: false }, checklist: [{ item: "Radar calibration", completed: false }, { item: "GPS accuracy verification", completed: false }, { item: "VHF radio range test", completed: false }, { item: "GMDSS equipment check", completed: false }, { item: "AIS transponder verification", completed: false }], created_at: d(-12) },
  { id: "j005", vessel_id: "v004", vessel_name: "MV Pearl Voyager", ship_manager: "BSM Ship Management Mumbai", ship_owner: "SCI India", vessel_type: "Chemical Tanker", port: "Kochi", berth: "B-02", eta: d(8), etd: d(72), service_type: "FFA", cert_expiry_date: d(-24 * 2), cert_days_remaining: -2, cert_status: "expired", status: "flagged", next_port: { name: "Fujairah", code: "ARE", covered: false }, checklist: [{ item: "Fire extinguisher inspection", completed: false }, { item: "Fire hose pressure test", completed: false }, { item: "Fixed CO2 system check", completed: false }, { item: "Fire detection alarm test", completed: false }, { item: "Breathing apparatus service", completed: false }], created_at: d(-36) },
  { id: "j006", vessel_id: "v005", vessel_name: "MV Golden Horizon", ship_manager: "V.Ships Singapore", ship_owner: "HPCL", vessel_type: "Product Tanker", port: "Chennai", berth: "B-15", eta: d(1), etd: d(40), service_type: "LSA", cert_expiry_date: d(24 * 14), cert_days_remaining: 14, cert_status: "warning", status: "pending", next_port: { name: "Shanghai", code: "CHN", covered: false }, checklist: [{ item: "Lifeboat inspection", completed: false }, { item: "Life raft servicing", completed: false }, { item: "Life jacket count & condition", completed: false }, { item: "EPIRB battery test", completed: false }, { item: "Pyrotechnics expiry check", completed: false }], created_at: d(-8) },
  { id: "j007", vessel_id: "v006", vessel_name: "MV Sapphire Sea", ship_manager: "Wallem Shipmanagement Hong Kong", ship_owner: "Reliance Industries", vessel_type: "General Cargo", port: "Vizag", berth: "B-09", eta: d(5), etd: d(55), service_type: "LSA", cert_expiry_date: d(24 * 5), cert_days_remaining: 5, cert_status: "critical", status: "in_progress", next_port: { name: "Rotterdam", code: "NLD", covered: false }, checklist: [{ item: "Lifeboat inspection", completed: true }, { item: "Life raft servicing", completed: true }, { item: "Life jacket count & condition", completed: true }, { item: "EPIRB battery test", completed: false }, { item: "Pyrotechnics expiry check", completed: false }], created_at: d(-20) },
  { id: "j008", vessel_id: "v007", vessel_name: "MV Iron Monarch", ship_manager: "Thome Ship Management Singapore", ship_owner: "Adani Logistics", vessel_type: "Bulk Carrier", port: "Mundra", berth: "B-18", eta: d(3), etd: d(45), service_type: "LSA", cert_expiry_date: d(24 * 2), cert_days_remaining: 2, cert_status: "critical", status: "pending", next_port: { name: "Yokohama", code: "JPN", covered: false }, checklist: [{ item: "Lifeboat inspection", completed: false }, { item: "Life raft servicing", completed: false }, { item: "Life jacket count & condition", completed: false }, { item: "EPIRB battery test", completed: false }, { item: "Pyrotechnics expiry check", completed: false }], created_at: d(-16) },
  { id: "j009", vessel_id: "v007", vessel_name: "MV Iron Monarch", ship_manager: "Thome Ship Management Singapore", ship_owner: "Adani Logistics", vessel_type: "Bulk Carrier", port: "Mundra", berth: "B-18", eta: d(3), etd: d(45), service_type: "FFA", cert_expiry_date: d(24 * 7), cert_days_remaining: 7, cert_status: "critical", status: "flagged", next_port: { name: "Yokohama", code: "JPN", covered: false }, checklist: [{ item: "Fire extinguisher inspection", completed: false }, { item: "Fire hose pressure test", completed: false }, { item: "Fixed CO2 system check", completed: false }, { item: "Fire detection alarm test", completed: false }, { item: "Breathing apparatus service", completed: false }], created_at: d(-16) },
  { id: "j010", vessel_id: "v009", vessel_name: "MV Crystal Wave", ship_manager: "Executive Ship Management Singapore", ship_owner: "Safe Bulkers Inc", vessel_type: "Bulk Carrier", port: "Mumbai", berth: "B-22", eta: d(6), etd: d(65), service_type: "LSA", cert_expiry_date: d(-24 * 1), cert_days_remaining: -1, cert_status: "expired", status: "in_progress", next_port: { name: "Singapore", code: "SGP", covered: false }, checklist: [{ item: "Lifeboat inspection", completed: true }, { item: "Life raft servicing", completed: false }, { item: "Life jacket count & condition", completed: false }, { item: "EPIRB battery test", completed: false }, { item: "Pyrotechnics expiry check", completed: false }], created_at: d(-30) },
  { id: "j011", vessel_id: "v011", vessel_name: "MV Neptune's Grace", ship_manager: "Synergy Marine Singapore", ship_owner: "Eastern Bulk Carriers AS", vessel_type: "Chemical Tanker", port: "Kochi", berth: "B-14", eta: d(2), etd: d(38), service_type: "FFA", cert_expiry_date: d(24 * 1), cert_days_remaining: 1, cert_status: "critical", status: "acknowledged", next_port: { name: "Colombo", code: "LKA", covered: false }, checklist: [{ item: "Fire extinguisher inspection", completed: true }, { item: "Fire hose pressure test", completed: true }, { item: "Fixed CO2 system check", completed: false }, { item: "Fire detection alarm test", completed: false }, { item: "Breathing apparatus service", completed: false }], created_at: d(-18) },
  { id: "j012", vessel_id: "v013", vessel_name: "MV Phoenix Rising", ship_manager: "BSM Ship Management Mumbai", ship_owner: "Indian Oil Corporation", vessel_type: "General Cargo", port: "Vizag", berth: "B-01", eta: d(15), etd: d(100), service_type: "FFA", cert_expiry_date: d(24 * 8), cert_days_remaining: 8, cert_status: "critical", status: "pending", next_port: { name: "Fujairah", code: "ARE", covered: false }, checklist: [{ item: "Fire extinguisher inspection", completed: false }, { item: "Fire hose pressure test", completed: false }, { item: "Fixed CO2 system check", completed: false }, { item: "Fire detection alarm test", completed: false }, { item: "Breathing apparatus service", completed: false }], created_at: d(-4) },
  { id: "j013", vessel_id: "v014", vessel_name: "MV Blue Marlin", ship_manager: "V.Ships Dubai", ship_owner: "HPCL", vessel_type: "Bulk Carrier", port: "Mundra", berth: "B-16", eta: d(9), etd: d(75), service_type: "LSA", cert_expiry_date: d(-24 * 3), cert_days_remaining: -3, cert_status: "expired", status: "flagged", next_port: { name: "Rotterdam", code: "NLD", covered: false }, checklist: [{ item: "Lifeboat inspection", completed: false }, { item: "Life raft servicing", completed: false }, { item: "Life jacket count & condition", completed: false }, { item: "EPIRB battery test", completed: false }, { item: "Pyrotechnics expiry check", completed: false }], created_at: d(-40) },
  { id: "j014", vessel_id: "v016", vessel_name: "MV Indian Express", ship_manager: "Anglo-Eastern Ship Management Mumbai", ship_owner: "SCI India", vessel_type: "Container", port: "Tuticorin", berth: "B-12", eta: d(3), etd: d(48), service_type: "LSA", cert_expiry_date: d(24 * 9), cert_days_remaining: 9, cert_status: "critical", status: "pending", next_port: { name: "Hamburg", code: "DEU", covered: false }, checklist: [{ item: "Lifeboat inspection", completed: false }, { item: "Life raft servicing", completed: false }, { item: "Life jacket count & condition", completed: false }, { item: "EPIRB battery test", completed: false }, { item: "Pyrotechnics expiry check", completed: false }], created_at: d(-14) },
  { id: "j015", vessel_id: "v018", vessel_name: "MV Tiger Bay", ship_manager: "Columbia Shipmanagement Limassol", ship_owner: "Pacific Basin Shipping", vessel_type: "Bulk Carrier", port: "Chennai", berth: "B-17", eta: d(11), etd: d(85), service_type: "FFA", cert_expiry_date: d(-24 * 4), cert_days_remaining: -4, cert_status: "expired", status: "flagged", next_port: { name: "Dubai", code: "ARE", covered: false }, checklist: [{ item: "Fire extinguisher inspection", completed: false }, { item: "Fire hose pressure test", completed: false }, { item: "Fixed CO2 system check", completed: false }, { item: "Fire detection alarm test", completed: false }, { item: "Breathing apparatus service", completed: false }], created_at: d(-25) },
  { id: "j016", vessel_id: "v021", vessel_name: "MV Deccan Queen", ship_manager: "Fleet Management Ltd Mumbai", ship_owner: "GE Shipping", vessel_type: "Bulk Carrier", port: "Mundra", berth: "B-19", eta: d(1), etd: d(35), service_type: "LSA", cert_expiry_date: d(24 * 3), cert_days_remaining: 3, cert_status: "critical", status: "in_progress", next_port: { name: "Fujairah", code: "ARE", covered: false }, checklist: [{ item: "Lifeboat inspection", completed: true }, { item: "Life raft servicing", completed: true }, { item: "Life jacket count & condition", completed: true }, { item: "EPIRB battery test", completed: true }, { item: "Pyrotechnics expiry check", completed: false }], created_at: d(-50) },
  { id: "j017", vessel_id: "v021", vessel_name: "MV Deccan Queen", ship_manager: "Fleet Management Ltd Mumbai", ship_owner: "GE Shipping", vessel_type: "Bulk Carrier", port: "Mundra", berth: "B-19", eta: d(1), etd: d(35), service_type: "FFA", cert_expiry_date: d(-24 * 6), cert_days_remaining: -6, cert_status: "expired", status: "flagged", next_port: { name: "Fujairah", code: "ARE", covered: false }, checklist: [{ item: "Fire extinguisher inspection", completed: false }, { item: "Fire hose pressure test", completed: false }, { item: "Fixed CO2 system check", completed: false }, { item: "Fire detection alarm test", completed: false }, { item: "Breathing apparatus service", completed: false }], created_at: d(-50) },
  { id: "j018", vessel_id: "v022", vessel_name: "MV Malabar Spirit", ship_manager: "V.Ships Dubai", ship_owner: "Essar Shipping", vessel_type: "Container", port: "Mumbai", berth: "B-21", eta: d(14), etd: d(95), service_type: "NAVCOM", cert_expiry_date: d(24 * 10), cert_days_remaining: 10, cert_status: "critical", status: "acknowledged", next_port: { name: "Rotterdam", code: "NLD", covered: false }, checklist: [{ item: "Radar calibration", completed: true }, { item: "GPS accuracy verification", completed: false }, { item: "VHF radio range test", completed: false }, { item: "GMDSS equipment check", completed: false }, { item: "AIS transponder verification", completed: false }], created_at: d(-11) },
  { id: "j019", vessel_id: "v024", vessel_name: "MV Gujarat Pride", ship_manager: "Anglo-Eastern Ship Management Hong Kong", ship_owner: "HPCL", vessel_type: "Product Tanker", port: "Kandla", berth: "B-23", eta: d(0.5), etd: d(28), service_type: "LSA", cert_expiry_date: d(-24 * 8), cert_days_remaining: -8, cert_status: "expired", status: "flagged", next_port: { name: "Dubai", code: "ARE", covered: false }, checklist: [{ item: "Lifeboat inspection", completed: false }, { item: "Life raft servicing", completed: false }, { item: "Life jacket count & condition", completed: false }, { item: "EPIRB battery test", completed: false }, { item: "Pyrotechnics expiry check", completed: false }], created_at: d(-60) },
  { id: "j020", vessel_id: "v024", vessel_name: "MV Gujarat Pride", ship_manager: "Anglo-Eastern Ship Management Hong Kong", ship_owner: "HPCL", vessel_type: "Product Tanker", port: "Kandla", berth: "B-23", eta: d(0.5), etd: d(28), service_type: "FFA", cert_expiry_date: d(24 * 2), cert_days_remaining: 2, cert_status: "critical", status: "pending", next_port: { name: "Dubai", code: "ARE", covered: false }, checklist: [{ item: "Fire extinguisher inspection", completed: false }, { item: "Fire hose pressure test", completed: false }, { item: "Fixed CO2 system check", completed: false }, { item: "Fire detection alarm test", completed: false }, { item: "Breathing apparatus service", completed: false }], created_at: d(-60) },
];

export const MOCK_QUOTES = [
  { id: "q001", vessel_id: "v001", vessel_name: "MV Ocean Pride", ship_manager: "Anglo-Eastern Ship Management Mumbai", ship_owner: "GE Shipping", port: "Mumbai", service_types: ["LSA", "FFA"], amount: 285000, currency: "INR", status: "open", created_at: d(-96) },
  { id: "q002", vessel_id: "v003", vessel_name: "MV Star Navigator", ship_manager: "Fleet Management Ltd Mumbai", ship_owner: "Essar Shipping", port: "Kandla", service_types: ["LSA", "FFA", "NAVCOM"], amount: 420000, currency: "INR", status: "sent", created_at: d(-72) },
  { id: "q003", vessel_id: "v005", vessel_name: "MV Golden Horizon", ship_manager: "V.Ships Singapore", ship_owner: "HPCL", port: "Chennai", service_types: ["LSA"], amount: 135000, currency: "INR", status: "open", created_at: d(-48) },
  { id: "q004", vessel_id: "v007", vessel_name: "MV Iron Monarch", ship_manager: "Thome Ship Management Singapore", ship_owner: "Adani Logistics", port: "Mundra", service_types: ["LSA", "FFA"], amount: 310000, currency: "INR", status: "sent", created_at: d(-60) },
  { id: "q005", vessel_id: "v009", vessel_name: "MV Crystal Wave", ship_manager: "Executive Ship Management Singapore", ship_owner: "Safe Bulkers Inc", port: "Mumbai", service_types: ["LSA", "FFA"], amount: 265000, currency: "INR", status: "open", created_at: d(-36) },
  { id: "q006", vessel_id: "v012", vessel_name: "MV Coral Trader", ship_manager: "Fleet Management Ltd Mumbai", ship_owner: "GE Shipping", port: "Chennai", service_types: ["NAVCOM"], amount: 190000, currency: "INR", status: "open", created_at: d(-24) },
  { id: "q007", vessel_id: "v016", vessel_name: "MV Indian Express", ship_manager: "Anglo-Eastern Ship Management Mumbai", ship_owner: "SCI India", port: "Tuticorin", service_types: ["LSA", "FFA", "NAVCOM"], amount: 450000, currency: "INR", status: "sent", created_at: d(-18) },
  { id: "q008", vessel_id: "v021", vessel_name: "MV Deccan Queen", ship_manager: "Fleet Management Ltd Mumbai", ship_owner: "GE Shipping", port: "Mundra", service_types: ["LSA", "FFA"], amount: 295000, currency: "INR", status: "open", created_at: d(-120) },
  { id: "q009", vessel_id: "v024", vessel_name: "MV Gujarat Pride", ship_manager: "Anglo-Eastern Ship Management Hong Kong", ship_owner: "HPCL", port: "Kandla", service_types: ["LSA", "FFA"], amount: 320000, currency: "INR", status: "open", created_at: d(-144) },
  { id: "q010", vessel_id: "v022", vessel_name: "MV Malabar Spirit", ship_manager: "V.Ships Dubai", ship_owner: "Essar Shipping", port: "Mumbai", service_types: ["NAVCOM"], amount: 175000, currency: "INR", status: "sent", created_at: d(-30) },
];

export const MOCK_LEADS = [
  { id: "l001", vessel_name: "MV Atlantic Spirit", ship_manager: "Synergy Marine Singapore", ship_owner: "Pacific Basin Shipping", port: "Mumbai", eta: d(24 * 3), service_types: ["LSA", "FFA"], source: "Port Authority", created_at: d(-48) },
  { id: "l002", vessel_name: "MV Bay Runner", ship_manager: "Fleet Management Ltd Mumbai", ship_owner: "Safe Bulkers Inc", port: "Kandla", eta: d(24 * 5), service_types: ["FFA"], source: "Agent Referral", created_at: d(-36) },
  { id: "l003", vessel_name: "MV Coral Sea", ship_manager: "V.Ships Dubai", ship_owner: "Eastern Bulk Carriers AS", port: "Kochi", eta: d(24 * 2), service_types: ["LSA", "NAVCOM"], source: "Website Inquiry", created_at: d(-24) },
  { id: "l004", vessel_name: "MV Delta Force", ship_manager: "BSM Ship Management Mumbai", ship_owner: "Tsakos Energy Navigation", port: "Chennai", eta: d(24 * 6), service_types: ["LSA", "FFA"], source: "Trade Show", created_at: d(-12) },
  { id: "l005", vessel_name: "MV Echo Bay", ship_manager: "Columbia Shipmanagement Limassol", ship_owner: "Reliance Industries", port: "Vizag", eta: d(24 * 4), service_types: ["FFA", "NAVCOM"], source: "Port Authority", created_at: d(-6) },
];

export const MOCK_NOTIFICATIONS = [
  { id: "n001", type: "cert_expiry", message: "MV Ocean Pride: LSA cert EXPIRED", vessel_name: "MV Ocean Pride", port: "Mumbai", severity: "expired", read: false, created_at: d(-12) },
  { id: "n002", type: "cert_expiry", message: "MV Ocean Pride: FFA cert expiring in 4d", vessel_name: "MV Ocean Pride", port: "Mumbai", severity: "critical", read: false, created_at: d(-10) },
  { id: "n003", type: "cert_expiry", message: "MV Pearl Voyager: FFA cert EXPIRED", vessel_name: "MV Pearl Voyager", port: "Kochi", severity: "expired", read: false, created_at: d(-8) },
  { id: "n004", type: "cert_expiry", message: "MV Iron Monarch: LSA cert expiring in 2d", vessel_name: "MV Iron Monarch", port: "Mundra", severity: "critical", read: true, created_at: d(-6) },
  { id: "n005", type: "cert_expiry", message: "MV Iron Monarch: FFA cert expiring in 7d", vessel_name: "MV Iron Monarch", port: "Mundra", severity: "critical", read: false, created_at: d(-5) },
  { id: "n006", type: "cert_expiry", message: "MV Crystal Wave: LSA cert EXPIRED", vessel_name: "MV Crystal Wave", port: "Mumbai", severity: "expired", read: false, created_at: d(-4) },
  { id: "n007", type: "cert_expiry", message: "MV Neptune's Grace: FFA cert expiring in 1d", vessel_name: "MV Neptune's Grace", port: "Kochi", severity: "critical", read: false, created_at: d(-3) },
  { id: "n008", type: "cert_expiry", message: "MV Blue Marlin: LSA cert EXPIRED", vessel_name: "MV Blue Marlin", port: "Mundra", severity: "expired", read: true, created_at: d(-2) },
  { id: "n009", type: "cert_expiry", message: "MV Deccan Queen: FFA cert EXPIRED", vessel_name: "MV Deccan Queen", port: "Mundra", severity: "expired", read: false, created_at: d(-2) },
  { id: "n010", type: "cert_expiry", message: "MV Gujarat Pride: LSA cert EXPIRED", vessel_name: "MV Gujarat Pride", port: "Kandla", severity: "expired", read: false, created_at: d(-1) },
  { id: "n011", type: "cert_expiry", message: "MV Gujarat Pride: FFA cert expiring in 2d", vessel_name: "MV Gujarat Pride", port: "Kandla", severity: "critical", read: false, created_at: d(-1) },
  { id: "n012", type: "cert_expiry", message: "MV Malabar Spirit: NAVCOM cert expiring in 10d", vessel_name: "MV Malabar Spirit", port: "Mumbai", severity: "critical", read: false, created_at: d(-0.5) },
];

export const MOCK_FILTERS = {
  managers: ["Anglo-Eastern", "Synergy Marine", "Fleet Management Ltd", "BSM Mumbai", "GE Shipping", "SCI India", "Tolani Shipping", "Essar Shipping"],
  owners: ["HPCL", "Indian Oil", "GE Shipping", "Essar Shipping", "SCI India", "Reliance Industries", "Adani Ports"],
};
